// create-hush-cli/templates/template-react/src/App.tsx
import { Suspense } from 'react';
import { ErrorBoundary } from 'react-error-boundary';

import { ErrorFallback, Loading } from '@/features';

import Routes from './routers';

function App() {
	return (
		<>
			<Suspense fallback={<Loading />}>
				<ErrorBoundary fallback={<ErrorFallback />}>
					<Routes />
				</ErrorBoundary>
			</Suspense>
		</>
	);
}

export default App;

// create-hush-cli/templates/template-vue/src/App.vue
<template>
	<RouterView v-slot="{ Component }">
		<template v-if="Component">
			<Transition mode="out-in">
				<Suspense>
					<component :is="Component"></component>
					<template #fallback> <Loading /> </template>
				</Suspense>
			</Transition>
		</template>
	</RouterView>
</template>

<script setup lang="ts">
import { Loading } from '@/features';
</script>

<style scoped></style>
